FROM golang:1.19.1 AS builder


WORKDIR /src/
COPY . .


RUN go build -o /app/webapi ./cmd/webapi


FROM debian:bullseye


EXPOSE 3000 4000

RUN mkdir -p /app/storage
COPY storage/default_profile_photo.jpg /app/storage/default_profile_photo.jpg


WORKDIR /app/
COPY --from=builder /app/webapi ./


CMD ["/app/webapi"]